#!/bin/csh
if("$1" != "") then
	set d=($1)
else
	set d=(/dev/cu.usbmodem61*)
endif

if($#d == 0) then
	echo No device
	exit 0
endif
again:
idf.py flash --port $d[1]
if($status) goto again

components/ESP32-RevK/idfmon $d[1]
goto again
